[package]
name = "nanowave"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2.5.0"
chrono = "0.4.44"
smol = "2.0.2"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time", "io-std"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
tracing-appender = "0.2"
clap = { version = "4.6.1", features = ["derive"] }
rodio = { git = "https://github.com/RustAudio/rodio.git", branch="master" }
media_source = { path = "../media_source" }

#[target.'cfg(not(target = "mipsel-unknown-linux-musl"))'.dependencies]
#slint = { git = "https://github.com/slint-ui/slint", branch = "master"} #, default-features=false, features=["backend-linuxkms-noseat", "renderer-software", "compat-1-2" ]}
#[target.mipsel-unknown-linux-musl.dependencies]
slint = { git = "https://github.com/slint-ui/slint", branch="master" } #branch = "master"} # , default-features=false, features=["backend-linuxkms-noseat", "renderer-software", "compat-1-2" ]}
# libc = "0.2.186"

[build-dependencies]
# [target.'cfg(not(target = "mipsel-unknown-linux-musl"))'.build-dependencies]
# slint-build = { git = "https://github.com/slint-ui/slint", branch = "master"} #, default-features=false, features=[ "renderer-software", "compat-1-18"]}
# [target.mipsel-unknown-linux-musl.build-dependencies]
slint-build = { git = "https://github.com/slint-ui/slint", branch="master"} #, branch = "master", default-features=false, features=[ "renderer-software", "compat-1-18"]}




[patch.crates-io]
# 38809fb ist zu neu
#fontique = { git = "https://github.com/linebender/parley.git",  rev="167da20" } # , rev="167da20"
#parley = { git = "https://github.com/linebender/parley.git",  rev="167da20" }
#parlance = { git = "https://github.com/linebender/parley.git",  rev="167da20" }
#cpal = {git = "https://github.com/RustAudio/cpal.git", branch = "fix/32bit-atomic-u64"}
# hiby has an eventloop timer bug
# calloop = "=0.14.4"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"
strip = true
