[target.mipsel-unknown-linux-musl]
image = "hiby-r1-cross:latest"
linker = "mipsel-linux-gcc"
rustflags = ["-C", "link-args=-static"]

[build.env]
passthrough = [
    "SDK=/project/buildroot/buildroot-2025.02.2/output/host",
    "PREFIX=mipsel-linux",
    "SYSROOT=/project/buildroot/buildroot-2025.02.2/output/host/mipsel-buildroot-linux-musl/sysroot",
    "PKG_CONFIG_ALLOW_CROSS=1",
    "PKG_CONFIG_PATH=/project/buildroot/buildroot-2025.02.2/output/host/mipsel-buildroot-linux-musl/sysroot/usr/lib/pkgconfig",
    "PKG_CONFIG_SYSROOT_DIR=/project/buildroot/buildroot-2025.02.2/output/host/mipsel-buildroot-linux-musl/sysroot",
    "PKG_CONFIG_LIBDIR=/project/buildroot/buildroot-2025.02.2/output/host/usr/lib/pkgconfig:/project/buildroot/buildroot-2025.02.2/output/host/usr/share/pkgconfig",
    "CC_mipsel_unknown_linux_musl=mipsel-linux-gcc",
    "CXX_mipsel_unknown_linux_musl=mipsel-linux-g++",
    "AR_mipsel_unknown_linux_musl=mipsel-linux-ar",
    "AS_mipsel_unknown_linux_musl=mipsel-linux-as",
    "LD_mipsel_unknown_linux_musl=mipsel-linux-ld",
    "NM_mipsel_unknown_linux_musl=mipsel-linux-nm",
    "STRIP_mipsel_unknown_linux_musl=mipsel-linux-strip",
    "RANLIB_mipsel_unknown_linux_musl=mipsel-linux-ranlib"
]

# SDK="/project/buildroot/buildroot-2025.02.2/output/host"
# PREFIX="mipsel-linux"
# SYSROOT="/project/buildroot/buildroot-2025.02.2/output/host/mipsel-buildroot-linux-musl/sysroot"

# SYSROOT=$("$SDK/bin/${PREFIX}-gcc" -print-sysroot)
# export PATH="$SDK/bin:$PATH"
# export CC_mipsel_unknown_linux_musl="${PREFIX}-gcc"
# export CXX_mipsel_unknown_linux_musl="${PREFIX}-g++"
# export AR_mipsel_unknown_linux_musl="${PREFIX}-ar"
# export AS_mipsel_unknown_linux_musl="${PREFIX}-as"
# export LD_mipsel_unknown_linux_musl="${PREFIX}-ld"
# export NM_mipsel_unknown_linux_musl="${PREFIX}-nm"
# export STRIP_mipsel_unknown_linux_musl="${PREFIX}-strip"
# export RANLIB_mipsel_unknown_linux_musl="${PREFIX}-ranlib"

# export PKG_CONFIG_ALLOW_CROSS=1
# export PKG_CONFIG_SYSROOT_DIR="$SYSROOT"
# export PKG_CONFIG_LIBDIR="$SYSROOT/usr/lib/pkgconfig:$SYSROOT/usr/share/pkgconfig"
