export global SlintPreferences {
    in-out property <bool> enable-gestures: true;
    in-out property <bool> enable-statusbar: true;
    in-out property <ColorScheme> color-scheme: ColorScheme.dark;

    /*
    callback user_interaction();
    callback sync();

    in-out property <string> now: "";

    // in-out property <bool> fullscreen: false;
    in-out property <float> brightness: 0.3;

    in-out property <bool> enable-touch-events: true;
    in-out property <bool> display-color-test: false;

    */
}