export global SlintIcons {
    // home
    in-out property <image> audiobooks: @image-url("../images/icons/home/audiobooks.png");
    in-out property <image> music: @image-url("../images/icons/home/music.png");
    in-out property <image> search: @image-url("../images/icons/home/search.png");
    in-out property <image> settings: @image-url("../images/icons/home/settings.png");
    // player
    in-out property <image> next: @image-url("../images/icons/player/skip_next.png");
    in-out property <image> previous: @image-url("../images/icons/player/skip_previous.png");
    in-out property <image> pause: @image-url("../images/icons/player/pause.png");
    in-out property <image> play: @image-url("../images/icons/player/play_arrow.png");
    in-out property <image> forward-5: @image-url("../images/icons/player/forward_5.png");
    in-out property <image> forward-10: @image-url("../images/icons/player/forward_10.png");
    in-out property <image> forward-30: @image-url("../images/icons/player/forward_30.png");
    in-out property <image> replay-5: @image-url("../images/icons/player/replay_5.png");
    in-out property <image> replay-10: @image-url("../images/icons/player/replay_10.png");
    in-out property <image> replay-30: @image-url("../images/icons/player/replay_30.png");
}