# this seems to be required, because linker is ignored in Cross.toml
[target.mipsel-unknown-linux-musl]
linker = "/project/buildroot/buildroot-2025.02.2/output/host/bin/mipsel-buildroot-linux-musl-gcc"

rustflags = ["-C", "link-args=-static"]
# rustflags = ["-C", "target-feature=+crt-static"] # does not work, eudev prevents using fully static builds