
import { VerticalBox, Button, Palette, Slider, GridBox, HorizontalBox } from "std-widgets.slint";
import {HomeButtonItem, SlintIcons, SlintNavigation, SlintPreferences} from "./types.slint";
import {StatusBar} from "./components.slint";

export component App inherits Window {
    width: 368px;
    height: 552px; // height: root.height; // 552px;

    default-font-family: "Lato";
    default-font-size: 16pt;

    in property <[HomeButtonItem]> homeButtonItems: [
        { name: "music", label: "Music", icon: SlintIcons.music },
        { name: "audibooks", label: "Audiobooks", icon: SlintIcons.audiobooks },
        { name: "settings", label: "Settings", icon: SlintIcons.settings },
    ];

    property<int> columns: Math.max(1, Math.floor(root.width / 150px));
    property<int> rows: Math.max(1, Math.ceil(homeButtonItems.length / columns));
    property<length> tile-size: self.width / columns;

    init => {
        // load preferences
        // restore route
        Palette.color-scheme = SlintPreferences.color-scheme;
    }

    SwipeGestureHandler {
        x: 0;
        y: 0;
        width: root.width;
        height: root.height;
        handle-swipe-right: SlintPreferences.enable-gestures;
        handle-swipe-left: SlintPreferences.enable-gestures;
        swiped => {
            let xdiff = self.current-position.x - self.pressed-position.x;
            let ydiff = self.current-position.y - self.pressed-position.y;
            let is-horizontal-swipe = xdiff*xdiff > ydiff * ydiff;

            if (is-horizontal-swipe) {
                if (self.current-position.x > self.pressed-position.x) {
                    // debug("swipe: back");
                    SlintNavigation.offset(-1);
                } else if (self.current-position.x < self.pressed-position.x) {
                    // debug("swipe: forward");
                    SlintNavigation.offset(1);
                }
            } else if(!is-horizontal-swipe) {
                if (self.current-position.y > self.pressed-position.y) {
                    // debug("swipe: down");
                    SlintNavigation.path(["settings"]);
                } else if (self.current-position.y < self.pressed-position.y) {
                    debug("swipe: up");
                    /*
                    let item-id = SlintAudioPlayer.current-item.id;
                    if (item-id != "") {
                        SlintNavigation.path(["details", item-id]);
                    }
                    */
                }
            }
        }
    }



    VerticalBox {
        padding: 0;
        StatusBar {
            visible: SlintPreferences.enable-statusbar;
            width:100%;
            height:25px;
        }

        Flickable {
            interactive: false;
            width: 100%;

            VerticalBox {
                padding: 0px;
                spacing: 0px;

                // using properties for rows or columns does not work.
                // fixed values (rows=4, columns=2) do work
                for i in rows: HorizontalBox {
                    padding: 0px;
                    spacing: 0px;
                    for j in columns: Rectangle {
                        width: tile-size;
                        height: tile-size;
                        property <int> current-index: i * columns + j;
                        /*
                        background: #3b82f6;
                        Rectangle {
                            border-width: 1px;
                            border-color: #808080;
                            border-radius: 4px;
                        */
                            if current-index < homeButtonItems.length: VerticalBox {
                                alignment: center;
                                Image {
                                    horizontal-alignment: center;
                                    source: homeButtonItems[current-index].icon;
                                }
                                Text {
                                    horizontal-alignment: center;
                                    text: homeButtonItems[current-index].label;
                                }
                            }
                        /* } */
                    }
                }
            }
        }
    }

}