
import { VerticalBox, Button, Palette, Slider, GridBox, HorizontalBox } from "std-widgets.slint";
import {SlintNavigation, SlintPreferences} from "./globals.slint";
export component App inherits Window {
    default-font-family: "Lato";
    default-font-size: 16pt;

    init => {
        // load preferences
        // restore route
        Palette.color-scheme = SlintPreferences.color-scheme;
    }

    SwipeGestureHandler {
        x: 0;
        y: 0;
        width: root.width; // 368px;
        height: root.height; // 552px;
        handle-swipe-right: SlintPreferences.enable-gestures;
        handle-swipe-left: SlintPreferences.enable-gestures;
        swiped => {
            if (SlintPreferences.enable-gestures) {
                if (self.current-position.x > self.pressed-position.x) {
                    SlintNavigation.back()
                } else if (self.current-position.x < self.pressed-position.x) {
                    SlintNavigation.forward()
                }
            }
        }
    }

    in property <[string]> items: [
        "A", "B", "C", "D", "E", "F", "G"
    ];
    // property<length> spacing: 0px; // 16px;
    property<int> columns: Math.max(1, Math.floor(root.width / 150px));
    property<int> rows: Math.max(1, Math.ceil(items.length / columns));
    // property<length> columns-width: (columns - 1)  * spacing;
    property<length> tile-size: self.width / columns;
    Flickable {
        interactive: false;
        VerticalBox {
            padding: 0px;
            spacing: 0px;

            // using properties for rows or columns does not work.
            // fixed values (rows=4, columns=2) do work
            for i in rows: HorizontalBox {
                padding: 0px;
                spacing: 0px;
                for j in columns: Rectangle {
                    width: tile-size;
                    height: tile-size;
                    property <int> current-index: i * columns + j;
                    background: #3b82f6;
                    VerticalBox {
                        if current-index < items.length: Text {
                            text: items[current-index];
                        }
                    }
                }
            }
        }
    }
}