import {SlintIcons} from "./globals/SlintIcons.slint";
import {SlintNavigation} from "./globals/SlintNavigation.slint";
import {SlintPreferences} from "./globals/SlintPreferences.slint";
import {SlintStatus} from "./globals/SlintStatus.slint";


export {SlintIcons, SlintNavigation, SlintPreferences, SlintStatus}
/*
export global SlintCallbacks {
    pure callback format_duration(duration) -> string;
}

export struct SlintBatteryStatus {
    percent: float,
    charging: bool,
    health: string,
}


*/














/*
export global SlintFormatUtils {
    callback format-duration(duration) -> string;
    callback format-number()
}
*/

/*
export global SlintStatus {
    in-out property <SlintBatteryStatus> battery;
}
*/