import {SlintIcons} from "./types/SlintIcons.slint";
import {SlintNavigation} from "./types/SlintNavigation.slint";
import {SlintPreferences} from "./types/SlintPreferences.slint";

import {HomeButtonItem} from "./types/HomeButtonItem.slint";

export {SlintIcons, SlintNavigation, SlintPreferences}
export {HomeButtonItem}
/*
export global SlintCallbacks {
    pure callback format_duration(duration) -> string;
}

export struct SlintBatteryStatus {
    percent: float,
    charging: bool,
    health: string,
}


*/














/*
export global SlintFormatUtils {
    callback format-duration(duration) -> string;
    callback format-number()
}
*/

/*
export global SlintStatus {
    in-out property <SlintBatteryStatus> battery;
}
*/